### ISSUE TITLE
A11yWatch Integration

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#176]
[A11yWatch](https://a11ywatch.com/) provides super-fast website crawling. That speed is particularly useful when scanning giant sites.

To leverage that speed, the [A11yWatch API](https://a11ywatch.com/api-info) could be integrated into Equalify.

We would start by integrating with A11yWatch via `https://api.a11ywatch.com/api/scan`. Equalify would send a URL and then digest the JSON as alerts, the way that WAVE currently integrates (see https://github.com/bbertucc/equalify/blob/main/integrations/wave/functions.php). 

Further integrations would require a hook system (#174). The hook system would allow an A11yWatch integration to replace adders, add select components, and manipulate the scan.  

We should also consider Equalify's speed to display all the A11yWatch alerts. https://github.com/bbertucc/equalify/issues/142 would help with this speed issue.

Finally, let's talk cash... A11yWatch sells credits to use its service. When [creating an integration](https://github.com/bbertucc/equalify/wiki/Coding-an-Integration), there is currently no easy way to sell credits via an Equalify account. That needs to change. Equalify development could be sustained by taking a percentage of sales of A11yWatch.

In summary, here are the steps to integrate A11yWatch:
- [ ]  Ping with a single URL, like the WAVE integration does.
- [ ]  Integrate the crawler as an adder when we build hooks (#174)
- [ ]  Integrate A11yWatch components once we speed things up (#142)
- [ ]  Add A11yWatch to the Equalify Marketing once it's built (#175)

Some other pieces to consider:
- **Why not run A11yWatch via a sidercar (like @j-mendez setup here?** https://github.com/bbertucc/equalify/pull/153) My only concern is adding extra steps to launch the self-hosted version of Equalify. `!!EQUALIFY IS FOR EVERYONE!!` is in the head of every file, and Rust is not for everyone (unfortunately).
- **Can we just get going with an affiliate-style structure?** - I am open to it, but I don't know how much cash it will generate since most of our users are institutional clients.
- **Isn't A11yWatch a competitor of Equalify?** ... a few folks asked ... I def think we can help each other and are after a different space (I'm working with more admin-oriented people and I'm also focused on community, while @j-mendez is pushing the boundaries in ways serious devs will appreciate).

**Comment by j-mendez** [comment]
Hi, what is the roadblock with current integration using the crawl stream endpoint? Using a web-hook for data would not be ideal and not possible to hold in memory in the current architecture.

We expose the Stripe public key over the API `/api/client-key` and have built in components to help use it on the frontend. Adding uptime would be handled using the Stripe object once finished.

**Comment by j-mendez** [comment]
You also have all the data at the end of the stream the same play that a webhook would provide without needing the data held in memory on the server. Let me know if you have any questions.

**Comment by j-mendez** [comment]
The other bullets below some answers.

**Why not run A11yWatch via a sidercar**

1. Infrastructure.
2. Kernel for IO crawler may not be ideal for the OS and would not have a LB.

**Can we just get going with an affiliate-style structure? **
We have rewards here at https://a11ywatch.getrewardful.com/signup. ( You have to be accepted to get in and it may not be here forever. )

`Isn't A11yWatch a competitor of Equalify?`

Would the same question not apply to the other integrations? I am not sure how A11yWatch differs from a SaaS providing a good service.

--
Im not sure about the talk on money? If you integrate Google or Github sign-on that is a product addition and has nothing to do with the other-side. The features provided and exposed from A11yWatch enhance products and has nothing to do with outside aspects.

**Comment by bbertucc** [comment]
To keep the Equalify installation process as simple as possible, I imagine we can create a ddev recipe that gets both equalify and A11yWatch running with one command, similar to [what I envisioned with an axe-core ddev recipe](https://github.com/drud/ddev/issues/4406).

**Comment by bbertucc** [comment]
Adding the great news that there's a ddev integration!!!... https://github.com/a11ywatch/ddev-a11ywatch .. this will make integrating all the easier

**Comment by bbertucc** [comment]
#198 solves this.
