### ISSUE TITLE
Tune Equalify Scan after Initial WordPress.org Remediation is Complete

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#315]
After EqualifyEverything/eudaimonia-wp#1 we'll tune the Equalify scan. Equalify is made to be tuned for organizational interests.

This ticket will keep track of lessons learned so that we can tune the scan to report WordPress accessibility interests more accurately.

Here is our list of things to tune:

- [x] Do not report scan errors as violation. For instance, we report "Element's background color could not be determined due to a pseudo element" in the violation count. See: https://docs.google.com/spreadsheets/d/1pKDGP6-lHG85aYELv7Rk7hkfxQvF81ki8Vssq_w3GS0/edit?usp=sharing
- [ ] Only send single issues to our GPT tool. Batching issues, like missing alt text, just doesn't work
- [ ] Skip raw image URLs. See https://github.com/WordPress/wporg-main-2022/issues/462#issuecomment-2209548165
- [x] Alert when `alt=“”` so images can be further reviewed, as noted here: https://github.com/WordPress/wporg-main-2022/issues/462#issuecomment-2209653746
- [ ] Add Bulk ticket generation. Here's example UX: 1) Select which messages and properties you want to include, 2) output CSV with message, node, and URL 3) Generate ticket via [ChatGPT Bulk GPT](https://chatgpt.com/g/g-PzEnxEm8E-equalify-bulk-issue-ticket-creator) - [Example Ticket (link)](https://github.com/WordPress/wporg-main-2022), [Example Ticket 2](https://github.com/WordPress/wporg-main-2022/issues/473)
- [ ] Ignore duplicates if violations are similar, as noted here: https://github.com/WordPress/wporg-main-2022/issues/473#issuecomment-2229426163

**Comment by bbertucc** [comment]
Scheduled to discuss this at our next Monday Equalify contributors meeting

**Comment by bbertucc** [comment]
@azdak particularly curious how you think we can apply this type of tuning the the scan.

**Comment by bbertucc** [comment]
To do:
- [ ] create new issue for skipping media files
- [ ] test to see where axe is creating duplicate heading order issues
- [ ] Scope out adding a new message type that would handle errors versus violations
- [ ] add new issue to pass custom rule for `alt=""`, sending back a warning (versus a violation)

the new GPT tool should take care of the rest.

**Comment by bbertucc** [comment]
Closing this issue because two currently active tickets take care of the issues:

- https://github.com/EqualifyEverything/equalify/issues/464
- https://github.com/EqualifyEverything/equalify/issues/365
