### ISSUE TITLE
Build Sales Funnel

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#330]
## What is it?
Some of this is based off my meeting with @bbertucc earlier today. Some of it is my own gigantic braindump and since I'm a foodie through and through. C'mon don't always need to be professional, do we? The human element transcends our outreach work and I think we should be this way internally, too.

Imagine you want to share a delicious pie:
- Awareness: Tell people about your pie.
- Interest: Some people get curious.
- Consideration: They ask more questions.
- Intent: They decide they want a slice.
- Purchase: They get a slice.
- Loyalty: They love it and come back for more.
## Todo (fluid)
- [x] Meet with Blake and Kevin Francis from Salesforce on June 13. Ask lots of great questions and then shut up and listen.
- [x] @bbertucc to post a link to the video about the numbers, conversions, etc in the next few days, if possible.
- [x] Follow up with Mark Jamison at Khan Academy one more time by Friday this week. Send him my Calendly link.
- [x] Take some time to do research over the next several days about what an effective sales funnel looks like. Aim to have something written up even if just some solid notes for my meeting with Blake on June 19 to be able to articulate strategy and walk through the workflow.
- [x] Post sales funnel as a document after it's fleshed out with my meeting with @bbertucc on the 19th.
## Other Notes from Our Meeting
- 1:1 with Blake:
  - Discuss sales funnel strategy.
  - Review email outreach plan.
  - Analyze the list of contacts and their titles.
  - Develop approach to convert different types of contacts into purchasers.
  - Plan tailored emails for buyers and introducers.
  - Outline content for each stage of the sales process.
  - Discuss budget and lead conversion rates.
  
- **Email Outreach Strategy:**
  - Identify Target Contacts: Review titles and roles.
  - Tailor Messages:
    - Email 1: Target potential buyers.
    - Email 2: Reach out to contacts who can introduce you

**Comment by bbertucc** [comment]
@kevinandrews1 Two Links for you:
- Video on Rough Ideas Around Outreach Targets: https://www.youtube.com/watch?v=jCSn3YFEwRE
- Detailed Breakdown on Rough Outreach Targets: https://github.com/EqualifyEverything/equalify-outreach/blob/main/TARGETS.md

**Comment by bbertucc** [comment]
Also @kevinandrews1 - I suggest adding one more todo item: Post sales funnel. You can post it to the repo as a markdown file (I can show you how) or you can add it to our Google Drive. Whatever you want.

**Comment by bbertucc** [comment]
This is done. We posted the sales funnel to the outreach drive.
