### ISSUE TITLE
Video Pitch

### ISSUE THREAD

**Issue by kevinandrews1** [bbertucc/equalify#331]
## Goals and Objectives
- This needs to get people to sign up to be notified of the V1 launch.

## To-do list for video pitch
- [x] Confirm with @wilsuriel03 and @heythisischris front-end issues are addressed on June 21.
- [x] Regression testing a11y https://github.com/EqualifyEverything/equalify-frontend/issues/10 and @bbertucc will test by June 24.
- [x] Record pitch video on June 26 in the afternoon.
- [ ] Post the pitch on the Equalify website. with sign-up form
- [ ] Post on social media including LinkedIn, X, and my Fb.
- [ ] Email it to the Braintrust and contacts.

**Comment by kevinandrews1** [comment]
We've done the issue videos but not a pitch unless we wanna show managed? I'd love to be able to demo dashboard @bbertucc but can close this since we're going to create another issue re UFA and video series. Feel free to reopen if you disagree.
