### ISSUE TITLE
July 2024 Release Task List

### ISSUE THREAD

**Issue by heythisischris** [bbertucc/equalify#334]
- [x] Move Equalify Schema response to `get/results/schema`, new React-friendly response to `get/results/all`. The reason behind this is to have the backend correctly format duplicate messages and provide charting data at the same time.
- [x] Create distinct endpoints for drilling down into messages, tags, & urls: `get/results/messages`, `get/results/tags`, `get/results/urls`
- [x] Make sure to include table of charting data for accessibility, hide using aria labels (hide chart for screen-readers, show table for screen-readers)
- [x] Add "Get More Info" link to messages (copy markup)
- [x] Remove "add sitemap.xml" and update the label when adding property
- [x] Add "/" to the end of all URLs
- [x] Add dropdown to properties which specifies "Single" or "Sitemap", "Discovery Process" is the name of the column
- [x] Ensure users are only able to see their own rows (access control & permissions)
- [x] #343
- [x] #344
- [x] #345
- [x] #346
- [ ] Address any accessibility issues that Kevin reports
- [x] #347
- [x] #348
- [ ] When all is done, deploy to `equalify.app`

Signup URL: https://staging.equalify.dev/signup
Due date: July 8th, 2024

**Comment by heythisischris** [comment]
@bbertucc @kevinandrews1

**Comment by bbertucc** [comment]
@heythisischris we’ll deploy to `managed.equalify.app`, replacing what is there. There are really only three users we need to migrate over before we do that. I’ve added a step for that.

**Comment by bbertucc** [comment]
I added "Finalize Frontend Development". I realize that we didn't have that very crucial step LOL

**Comment by bbertucc** [comment]
Closing this issue in favor of individual issues I just opened.
