### ISSUE TITLE
Schema Documentation to Work toward V2 Roadmap Goals

### ISSUE THREAD

**Issue by bbertucc** [bbertucc/equalify#507]
## Problem
We're getting into the dangerous place of "database spaghetti code". The DB currently has about 50 different tables with different fields. That makes doing simple queries really complicated and difficult to figure out.

## Goal
Create a schema document that analyzes the current schema. From this document we'll create new issues around refining the DB Schema in V2 work.

## Steps to Close This Issue
- [ ] @bbertucc review issue with the assignee to make sure it can be accomplished within two weeks, or links to additional issues.
- [ ] Assignee budgets issues.
- [ ] Budget is approved/disapproved with comment.
- [ ] @azdak submits document for team review and create new issues.
- [ ] @bbertucc closes this issue after logging budget.

**Comment by bbertucc** [comment]
@heythisischris I assigned @azdak to this, but maybe you already have a schema doc?

**Comment by bbertucc** [comment]
Closing this because it's not part of our current dev push
